# if you want to try the docker as your development env:
# optional:
#     export WORKDIR="/$(basename $(pwd))"
##########################################################
# Run:
#   docker-compose run ubuntu-env
version: "3.8"
services:
  ubuntu-env:
    privileged: true
    build:
      context: .
    image: ghcr.io/ibm-xaas/ubuntu-env:main
    volumes:
      # For future ssh use in development
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - .:/ubuntu-env
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro
    environment:
      IBMCLOUD_API_KEY: "$IBMCLOUD_API_KEY"
    working_dir: /ubuntu-env
